
### Variables
@url = http://localhost:3000


### Get todos

### Get todos working!
GET {{url}}/api/todos


### Create a todo
POST {{url}}/api/todos
Content-Type: application/json

{
  "item": "Finish the Assignment"
}

### Toggle completed status of a todo

PUT {{url}}/todos


